version: 2

seeds:
  - name: taxi_zone_lookup
    description: NYC TLC taxi zone reference data (subset bundled for demo – replace via official dataset for production).
    columns:
      - name: location_id
        tests:
          - not_null
          - unique
