-- Dev environment bootstrap: separate dev database/schemas and role for dbt

-- 1) Create dedicated dev role
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS DBT_ETL_DEV
  COMMENT = 'Dev-only dbt role (write in ANALYTICS_DEV, read-only in ANALYTICS).';

GRANT ROLE DBT_ETL_DEV TO ROLE SYSADMIN;
GRANT ROLE DBT_ETL_DEV TO USER DBT_SVC;


-- 2) Create dev analytics database and schemas
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ANALYTICS_DEV COMMENT = 'Dev analytics database for dbt models';

CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.RAW    COMMENT = 'Dev landing/ingest layer';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.STAGE  COMMENT = 'Dev staging/cleanup layer';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.CORE   COMMENT = 'Dev modeled, conformed layer';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.MART   COMMENT = 'Dev presentation marts for BI';
CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.UTIL   COMMENT = 'Dev utilities (seeds, macros artifacts, UDFs, etc.)';


-- 3) Grants for DBT_ETL_DEV on dev database (full R/W)
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;
GRANT CREATE SCHEMA ON DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE SEQUENCE, CREATE TEMPORARY TABLE, CREATE TASK, CREATE STREAM
ON ALL SCHEMAS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT USAGE
ON FUTURE SCHEMAS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
ON FUTURE TABLES IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT USAGE
ON FUTURE SEQUENCES IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT USAGE
ON FUTURE STAGES IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT USAGE
ON FUTURE FILE FORMATS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;

GRANT SELECT ON FUTURE VIEWS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ETL_DEV;


-- 4) Read-only access for DBT_ETL_DEV to prod database ANALYTICS

GRANT USAGE ON DATABASE ANALYTICS TO ROLE DBT_ETL_DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE DBT_ETL_DEV;

GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS TO ROLE DBT_ETL_DEV;
GRANT SELECT ON ALL VIEWS  IN DATABASE ANALYTICS TO ROLE DBT_ETL_DEV;

GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS TO ROLE DBT_ETL_DEV;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE ANALYTICS TO ROLE DBT_ETL_DEV;
